-- MySQL schema for a simple login system

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_users_username (username),
  UNIQUE KEY uniq_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create a user (replace the hash with one generated by PHP's password_hash()).
-- Example snippet to generate a hash:
--   php -r "echo password_hash('yourPassword', PASSWORD_DEFAULT), PHP_EOL;"
--
-- INSERT INTO users (username, email, password_hash)
-- VALUES ('admin', 'admin@example.com', '$2y$10$...');

